services:
  postgres:
    image: postgres:15
    container_name: postgres_java_spring_chat_realtime
    environment:
      POSTGRES_DB: spring_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
